### ISSUE TITLE
why after dropbox website authenticate direct me to admin.com?

### ISSUE THREAD

**Issue by applemate** [Kendysond/Dropbox-Api-for-Codeigniter#3]
please see this video for what happen:

https://www.dropbox.com/s/vrhjppanyxqs1qg/bug.mp4?dl=0

**Comment by Kendysond** [comment]
Oops sorry i know why that happens i'll fix it in a bit,please be patient

**Comment by Kendysond** [comment]
The return link has been fixed on the New Commit
